// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVmH7pQehg3qObXACmZ5OFEbfHVzsMOU8',
    appId: '1:906489010002:web:6a66c2381ea788661dcc8b',
    messagingSenderId: '906489010002',
    projectId: 'zauntrack',
    authDomain: 'zauntrack.firebaseapp.com',
    storageBucket: 'zauntrack.appspot.com',
    measurementId: 'G-BKYFRQX579',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrLn_-JBHlluvSscuWE6G-6wRClwXvenA',
    appId: '1:906489010002:android:ce239b4b87ccfec21dcc8b',
    messagingSenderId: '906489010002',
    projectId: 'zauntrack',
    storageBucket: 'zauntrack.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2p7HqN7M8RumsN3YEj9JHZg7ZUg81fik',
    appId: '1:906489010002:ios:7eaef3a2ef604a831dcc8b',
    messagingSenderId: '906489010002',
    projectId: 'zauntrack',
    storageBucket: 'zauntrack.appspot.com',
    iosClientId: '906489010002-cauosr4e1tj0jj3fouvk5hsvrvtugqfr.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventoryManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2p7HqN7M8RumsN3YEj9JHZg7ZUg81fik',
    appId: '1:906489010002:ios:7eaef3a2ef604a831dcc8b',
    messagingSenderId: '906489010002',
    projectId: 'zauntrack',
    storageBucket: 'zauntrack.appspot.com',
    iosClientId: '906489010002-cauosr4e1tj0jj3fouvk5hsvrvtugqfr.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventoryManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVmH7pQehg3qObXACmZ5OFEbfHVzsMOU8',
    appId: '1:906489010002:web:3d7c3512c9fe4af11dcc8b',
    messagingSenderId: '906489010002',
    projectId: 'zauntrack',
    authDomain: 'zauntrack.firebaseapp.com',
    storageBucket: 'zauntrack.appspot.com',
    measurementId: 'G-71R0186JR7',
  );
}
